name: Test requirements.txt

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: The branch, tag, or revision to test.
        type: string
        required: true
  pull_request:
  schedule:
    - cron: "0 12 * * *"

permissions: {}

jobs:
  test_requirements:
    name: requirements.txt / ${{ matrix.python_version }}
    runs-on: ubuntu-latest

    env:
      SIGSTORE_REF: ${{ inputs.ref }}
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Populate reference from context
        if: ${{ env.SIGSTORE_REF == '' }}
        run: |
          echo "SIGSTORE_REF=${GITHUB_REF}" >> "${GITHUB_ENV}"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ env.SIGSTORE_REF }}
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
          cache: "pip"

      - name: Run test install
        run: python -m pip install --require-hashes --no-deps -r install/requirements.txt
