name: Test requirements.txt

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: The branch, tag, or revision to test.
        type: string
        required: true
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test_requirements:
    name: requirements.txt / ${{ matrix.python_version }}
    runs-on: ubuntu-latest

    env:
      SIGSTORE_REF: ${{ inputs.ref }}
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Populate reference from context
        if: ${{ env.SIGSTORE_REF == '' }}
        run: |
          echo "SIGSTORE_REF=${{ github.ref }}" >> "${GITHUB_ENV}"

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: ${{ env.SIGSTORE_REF }}

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"

      - name: Run test install
        run: python -m pip install -r install/requirements.txt
