name: Test requirements.txt

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: The branch, tag, or revision to test.
        type: string
        required: true
  pull_request:
  schedule:
    - cron: "0 12 * * *"

permissions: {}

jobs:
  test_requirements:
    name: requirements.txt / ${{ matrix.python_version }}
    runs-on: ubuntu-latest

    env:
      SIGSTORE_REF: ${{ inputs.ref }}
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Populate reference from context
        if: ${{ env.SIGSTORE_REF == '' }}
        run: |
          echo "SIGSTORE_REF=${GITHUB_REF}" >> "${GITHUB_ENV}"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ env.SIGSTORE_REF }}
          persist-credentials: false

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          allow-prereleases: true
          cache: "pip"

      - name: Run test install
        run: python -m pip install -r install/requirements.txt
